<a href="https://colab.research.google.com/github/sheikh-asiful-islam/Pandas_Playground/blob/main/Pandas_Playground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# DataFrame = 2-dimensional
# DataFrame takes python dictionary
# series and colours we have created at previous

car_data = pd.DataFrame({"Car make": series, "Colour": colours})
car_data

  Car make Colour
0      BMW    red
1   Toyota   Blue
2    Honda  White

In [ ]:
# DataFrame = 2-dimensional
# DataFrame takes python dictionary
# series and colours we have created at previous

car_data = pd.DataFrame({"Car make": series, "Colour": colours})
car_data

  Car make Colour
0      BMW    red
1   Toyota   Blue
2    Honda  White

In [ ]:
# DataFrame = 2-dimensional
# DataFrame takes python dictionary
# series and colours we have created at previous

car_data = pd.DataFrame({"Car make": series, "Colour": colours})
car_data

  Car make Colour
0      BMW    red
1   Toyota   Blue
2    Honda  White

In [ ]:
# DataFrame = 2-dimensional
# DataFrame takes python dictionary
# series and colours we have created at previous

car_data = pd.DataFrame({"Car make": series, "Colour": colours})
car_data

  Car make Colour
0      BMW    red
1   Toyota   Blue
2    Honda  White

In [9]:
# rename pandas as pd
import pandas as pd

In [ ]:
# 2 main data types (1.Series and 2.DataFrame)
series = pd.Series(["BMW", "Toyota", "Honda"])

In [ ]:
series

0       BMW
1    Toyota
2     Honda
dtype: object

In [ ]:
# series = 1 -dimentional

In [ ]:
colours = pd.Series(["red", "Blue", "White"])
colours

0      red
1     Blue
2    White
dtype: object

In [11]:
# DataFrame = 2-dimensional
# DataFrame takes python dictionary
# series and colours we have created at previous

car_data = pd.DataFrame({"Car make": series, "Colour": colours})
car_data

  Car make Colour
0      BMW    red
1   Toyota   Blue
2    Honda  White

In [24]:
# import data
from google.colab import files
uploaded = files.upload()

Saving car-sales.csv to car-sales (1).csv

In [26]:
car_sales = pd.read_csv("car-sales.csv")

In [28]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [31]:
# Exporting a data_frame
car_sales.to_csv("exported-car-sales.csv")

In [32]:
exported_car_sales = pd.read_csv("exported-car-sales.csv")
exported_car_sales

   Unnamed: 0    Make Colour  Odometer (KM)  Doors       Price
0           0  Toyota  White         150043      4   $4,000.00
1           1   Honda    Red          87899      4   $5,000.00
2           2  Toyota   Blue          32549      3   $7,000.00
3           3     BMW  Black          11179      5  $22,000.00
4           4  Nissan  White         213095      4   $3,500.00
5           5  Toyota  Green          99213      4   $4,500.00
6           6   Honda   Blue          45698      4   $7,500.00
7           7   Honda   Blue          54738      4   $7,000.00
8           8  Toyota  White          60000      4   $6,250.00
9           9  Nissan  White          31600      4   $9,700.00