<a href="https://colab.research.google.com/github/sheikh-asiful-islam/Pandas_Playground/blob/main/Pandas_Playground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# DataFrame = 2-dimensional
# DataFrame takes python dictionary
# series and colours we have created at previous

car_data = pd.DataFrame({"Car make": series, "Colour": colours})
car_data

  Car make Colour
0      BMW    red
1   Toyota   Blue
2    Honda  White

In [13]:
# DataFrame = 2-dimensional
# DataFrame takes python dictionary
# series and colours we have created at previous

car_data = pd.DataFrame({"Car make": series, "Colour": colours})
car_data

  Car make Colour
0      BMW    red
1   Toyota   Blue
2    Honda  White

In [14]:
# DataFrame = 2-dimensional
# DataFrame takes python dictionary
# series and colours we have created at previous

car_data = pd.DataFrame({"Car make": series, "Colour": colours})
car_data

  Car make Colour
0      BMW    red
1   Toyota   Blue
2    Honda  White

In [15]:
# DataFrame = 2-dimensional
# DataFrame takes python dictionary
# series and colours we have created at previous

car_data = pd.DataFrame({"Car make": series, "Colour": colours})
car_data

  Car make Colour
0      BMW    red
1   Toyota   Blue
2    Honda  White

In [16]:
# rename pandas as pd
import pandas as pd

In [17]:
# 2 main data types (1.Series and 2.DataFrame)
series = pd.Series(["BMW", "Toyota", "Honda"])

In [18]:
series

0       BMW
1    Toyota
2     Honda
dtype: object

In [19]:
# series = 1 -dimentional

In [20]:
colours = pd.Series(["red", "Blue", "White"])
colours

0      red
1     Blue
2    White
dtype: object

In [21]:
# DataFrame = 2-dimensional
# DataFrame takes python dictionary
# series and colours we have created at previous

car_data = pd.DataFrame({"Car make": series, "Colour": colours})
car_data

  Car make Colour
0      BMW    red
1   Toyota   Blue
2    Honda  White

In [22]:
# import data
from google.colab import files
uploaded = files.upload()

Saving car-sales.csv to car-sales.csv

In [23]:
car_sales = pd.read_csv("car-sales.csv")

In [24]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [25]:
# Exporting a data_frame
car_sales.to_csv("exported-car-sales.csv", index = False)

In [26]:
exported_car_sales = pd.read_csv("exported-car-sales.csv")
exported_car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

## Describe Data

In [27]:
# Attribute: holds data (no brackets) || Function (method): does an action (has brackets ())
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [28]:
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [29]:
car_columns = car_sales.columns
car_columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [30]:
car_sales.index

RangeIndex(start=0, stop=10, step=1)

In [31]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [32]:
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [33]:
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [41]:
car_sales.mean(numeric_only=True)

Odometer (KM)    78601.4
Doors                4.0
dtype: float64

In [43]:
car_prices = pd.Series([3000, 1500, 111250])
car_prices.mean()

np.float64(38583.333333333336)

In [44]:
car_sales.sum()

Make             ToyotaHondaToyotaBMWNissanToyotaHondaHondaToyo...
Colour               WhiteRedBlueBlackWhiteGreenBlueBlueWhiteWhite
Odometer (KM)                                               786014
Doors                                                           40
Price            $4,000.00$5,000.00$7,000.00$22,000.00$3,500.00...
dtype: object

In [45]:
car_sales["Doors"].sum()

np.int64(40)

In [46]:
len(car_sales)

10

In [47]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00